# This file contains hyperparameter settings for each Strategy used by ComboHold
# These parameters are generated by the freqtrade hyperopt command for each strategy

# To update strategy parameters, just cut&paste the "buy_params" contents from the strategy into the entry of the
# dictionary indexed by strategy name.
# It's done this way to make it easier to update (frequently)

strategyParameters = {}

# EMABounce presents an issue since sometimes there just is no solution. Set a default set of values:
strategyParameters["EMABounce"] = {
    "buy_diff": 0.065,
    "buy_long_period": 50,
    "buy_macd_enabled": False,
    "buy_short_period": 10,
}

# may be auto-generated below here:

# ComboHold hyper parameters
strategyParameters["ComboHold"] = {
    "buy_bbbhold_enabled": False,
    "buy_bigdrop_enabled": True,
    "buy_btcjump_enabled": False,
    "buy_btcndrop_enabled": True,
    "buy_btcnseq_enabled": True,
    "buy_emabounce_enabled": False,
    "buy_fisherbb_enabled": False,
    "buy_macdcross_enabled": False,
    "buy_ndrop_enabled": False,
    "buy_nseq_enabled": True,
}

# BBBHold
strategyParameters["BBBHold"] = {
    "buy_bb_gain": 0.01,
    "buy_fisher": 0.28,
    "buy_fisher_enabled": False,
    "buy_mfi": 10.0,
    "buy_mfi_enabled": False,
}

# BigDrop
strategyParameters["BigDrop"] = {
    "buy_bb_enabled": False,
    "buy_drop": 0.016,
    "buy_fisher": -0.44,
    "buy_fisher_enabled": True,
    "buy_mfi": 16.0,
    "buy_mfi_enabled": False,
    "buy_num_candles": 7,
}

# BTCJump
strategyParameters["BTCJump"] = {
    "buy_bb_gain": 0.01,
    "buy_btc_jump": 0.015,
    "buy_fisher": 0.97,
}

# BTCNDrop
strategyParameters["BTCNDrop"] = {
    "buy_bb_enabled": False,
    "buy_drop": 0.01,
    "buy_fisher": 0.48,
    "buy_fisher_enabled": False,
    "buy_mfi": 31.0,
    "buy_mfi_enabled": False,
    "buy_num_candles": 3,
}

# BTCNSeq
strategyParameters["BTCNSeq"] = {
    "buy_bb_enabled": False,
    "buy_bb_gain": 0.09,
    "buy_drop": 0.011,
    "buy_fisher": 0.54,
    "buy_fisher_enabled": False,
    "buy_num_candles": 7,
}

# EMABounce
strategyParameters["EMABounce"] = {
    "buy_long_period": 50,
    "buy_short_period": 10,
    "buy_diff": 0.065,
}

# FisherBB
strategyParameters["FisherBB"] = {
    "buy_bb_gain": 0.02,
    "buy_fisher": 0.73,
}

# MACDCross
strategyParameters["MACDCross"] = {
    "buy_adx": 28.0,
    "buy_adx_enabled": True,
    "buy_bb_enabled": False,
    "buy_bb_gain": 0.08,
    "buy_dm_enabled": False,
    "buy_fisher": 0.93,
    "buy_fisher_enabled": False,
    "buy_mfi": 21.0,
    "buy_mfi_enabled": True,
    "buy_neg_macd_enabled": False,
    "buy_period": 5,
    "buy_sar_enabled": False,
}

# NDrop
strategyParameters["NDrop"] = {
    "buy_bb_enabled": False,
    "buy_drop": 0.01,
    "buy_fisher": 0.21,
    "buy_fisher_enabled": True,
    "buy_mfi": 31.0,
    "buy_mfi_enabled": False,
    "buy_num_candles": 3,
}

# NSeq
strategyParameters["NSeq"] = {
    "buy_bb_enabled": False,
    "buy_drop": 0.01,
    "buy_fisher": 0.99,
    "buy_fisher_enabled": False,
    "buy_mfi": 39.0,
    "buy_mfi_enabled": False,
    "buy_num_candles": 3,
}